# Generated by Django 4.2.15 on 2024-08-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PowerMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_energy", models.BigIntegerField()),
                ("reactive_energy", models.BigIntegerField()),
                ("voltage_r", models.FloatField()),
                ("voltage_s", models.FloatField()),
                ("voltage_t", models.FloatField()),
                ("current_r", models.FloatField()),
                ("current_s", models.FloatField()),
                ("current_t", models.FloatField()),
                ("active_power", models.BigIntegerField()),
                ("reactive_power", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Power Meter",
                "verbose_name_plural": "Power Meters",
            },
        ),
    ]
