# Generated by Django 4.2.15 on 2024-09-09 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_airquality_heatsmokedetector_powermeter1_powermeter2_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airquality",
            options={},
        ),
        migrations.AlterModelOptions(
            name="heatsmokedetector",
            options={},
        ),
        migrations.AlterModelOptions(
            name="powermeter1",
            options={},
        ),
        migrations.AlterModelOptions(
            name="powermeter2",
            options={},
        ),
        migrations.AlterModelOptions(
            name="powermeter3",
            options={},
        ),
        migrations.AlterModelOptions(
            name="powermeter4",
            options={},
        ),
    ]
