# Generated by Django 4.2.15 on 2024-09-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_airquality_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airquality",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="heatsmokedetector",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="powermeter1",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="powermeter2",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="powermeter3",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="powermeter4",
            options={"managed": False},
        ),
    ]
