# Generated by Django 4.2.15 on 2024-09-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_airquality_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Digitalmultimeter",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("voltage", models.FloatField(blank=True, null=True)),
                ("current", models.FloatField(blank=True, null=True)),
                (
                    "effectiveenergy",
                    models.IntegerField(
                        blank=True, db_column="effectiveEnergy", null=True
                    ),
                ),
                (
                    "reactiveenergy",
                    models.IntegerField(
                        blank=True, db_column="reactiveEnergy", null=True
                    ),
                ),
                (
                    "apparentpower",
                    models.IntegerField(
                        blank=True, db_column="apparentPower", null=True
                    ),
                ),
                (
                    "powerfactor",
                    models.FloatField(blank=True, db_column="powerFactor", null=True),
                ),
                ("frequency", models.FloatField(blank=True, null=True)),
                ("harmonics", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("collection_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "DigitalMultiMeter",
                "managed": False,
            },
        ),
    ]
